### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by simphotonics** [marcelgarus/has_is_getters#3]
Hi, when trying to run: 

$ pub get 
from the folder **has_is_getters/example** I got the following error:

Because every version of has_is_getters_generator from path depends on has_is_getters from hosted and example depends on has_is_getters from path, has_is_getters_generator from path is forbidden. So, because example depends on has_is_getters_generator from path, version solving failed.

I had to change the dependencies to point to the hosted version of the packages **has_is_getters** and **has_is_getters_generator** to make it work.

**Comment by MarcelGarus** [comment]
Oh true, I'll change that
